# Generated by Django 2.0 on 2018-08-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='bookedTo',
            field=models.DateTimeField(null=True),
        ),
    ]
