# Generated by Django 2.0 on 2018-08-05 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0003_auto_20180804_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.TextField()),
                ('osType', models.CharField(max_length=50, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Requesting', max_length=30)),
                ('createdAt', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
